[package]
name = "heroku-deploy-notifier"
version = "0.1.0"
authors = ["Christopher Dignam <chris@dignam.xyz>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
